# Generated by Django 4.2.4 on 2024-07-12 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_manager_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Name',
            new_name='name',
        ),
    ]
