# Generated by Django 4.2.4 on 2024-07-14 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_team_created_by_team_manager_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='manager_name',
            new_name='manager',
        ),
        migrations.AlterField(
            model_name='manager',
            name='team',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_manager', to='user.team'),
        ),
    ]
