# Generated by Django 4.2.4 on 2024-07-16 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_remove_slot_team_name_1_remove_slot_team_name_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name_1', models.CharField(max_length=100)),
                ('team_name_2', models.CharField(blank=True, max_length=100, null=True)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.slot')),
            ],
        ),
    ]
