# Generated by Django 4.2.4 on 2024-07-16 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_fixture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='team_name_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
