# Generated by Django 4.2.4 on 2024-07-16 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_fixture'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
