# Generated by Django 4.2.4 on 2024-07-16 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_slot_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='available',
        ),
    ]
