# Generated by Django 4.2.4 on 2024-07-16 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_remove_slot_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
