# Generated by Django 4.2.4 on 2024-07-16 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_slot_available'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserve_slot',
            old_name='chosen_by',
            new_name='manager_name',
        ),
    ]
