# Generated by Django 4.2.4 on 2024-07-16 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_rename_chosen_by_reserve_slot_manager_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='slot',
            name='unique_turf_time',
        ),
        migrations.AddField(
            model_name='slot',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='slot',
            constraint=models.UniqueConstraint(fields=('turf_name', 'date', 'time'), name='unique_turf_date_time'),
        ),
    ]
